version: '3'

services:
  db:
    build: ./.docker/mongo
    ports:
      - 27017:27017
    volumes:
      - ./data/db:/data/db
    environment:
      MONGODB_ROOT_PASSWORD: root
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_REPLICA_SET_KEY: 123456
      MONGODB_DATABASE: nodechallenge
