services:

  db:
    build: ./.docker/mongo
    ports:
      - 27017:27017
    volumes:
      - ./data/db:/data/db
    environment:
      MONGODB_ROOT_PASSWORD: root
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_REPLICA_SET_KEY: 123456
      MONGODB_DATABASE: nodechallenge
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: nodechallenge
      MONGO_REPLICA_HOST: host.docker.internal

networks:
  my-network:
    external: true
